
spring:
  application:
    name: zuul-service

server:
  port: 8089

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    info-service:
      path: /info/**
      serviceId: INFO-SERVICE
    user-service:
      path: /user/**
      serviceId: SERVICE-USER

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000